name: Build Test

on:
  push:
    branches: [ ahmadmusa ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Create the .env file
    - name: Create .env file
      run: |
       echo "${{ secrets.ENV_VARS }}" > .env
       cat .env  # Debugging only, remove for production

    # Step 4: Build and Test with Docker Compose
    - name: Build and Test Docker Compose
      run: |
        docker compose -f docker-compose.yml config
        docker compose build
        docker compose up -d
        sleep 15 # Allow time for services to start
        docker ps # Verify containers are running
    - name: Tear Down Docker Containers
      run: docker compose down
